Traceback (most recent call last):
  File "/home/yk0581/h1bworkers/code/02_revelio_indiv_clean/get_rev_merged.py", line 13, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'
Traceback (most recent call last):
  File "/home/yk0581/h1bworkers/code/02_revelio_indiv_clean/get_rev_merged.py", line 12, in <module>
    os.chdir('/home/yk0581/h1bworkers/code')
    ^^
NameError: name 'os' is not defined. Did you forget to import 'os'?
Traceback (most recent call last):
  File "/home/yk0581/h1bworkers/code/02_revelio_indiv_clean/get_rev_merged.py", line 15, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'
